### ISSUE TITLE
fm_I2CIO.cpp:89:8: error: 'OUTPUT' was not declared in this scope

### ISSUE THREAD

**Issue by berkaysit** [jmparatte/jm_LiquidCrystal_I2C#2]
I have installed the library. And example code give this error message:

\Arduino\libraries\jm_LiquidCrystal_I2C\fm_I2CIO.cpp: In member function 'void fm_I2CIO::pinMode(uint8_t, uint8_t)':

C:\Users\xxxx\Documents\Arduino\libraries\jm_LiquidCrystal_I2C\fm_I2CIO.cpp:89:8: error: 'OUTPUT' was not declared in this scope

   if ( OUTPUT == dir )

        ^

**Comment by jmparatte** [comment]
I've published v1.0.2 which solves the problem. 
The library is in progress. Actually, it works only with AVR architecture because it uses jm_Wire library - an experimental fork of Wire library for AVR.
